### PR TITLE
[GLT-3839] Update interop for NextSeq 2000 support

### PR DESCRIPTION
**Pull request by avarsava**
JIRA Ticket: GLT-3839

- [X] Updates release notes
- [ ] Updates developer documentation

### CODE REVIEW

**Comment by avarsava** [comment]
Needs improvements: startDate, sequencerPosition, containerModel, sequencingKit, workflowType, and indexSequencing are all null

**Review by djcooke — APPROVED** [review]
I approve the parts I didn't do

**Comment by djcooke** [comment]
sequencerPosition: NextSeq 2000 only has one position, so null is correct
sequencingKit: we don't detect this for Illumina runs
workflowType: n/a for NextSeq 2000

**Comment by avarsava** [comment]
I can't approve my own PR but I approve the parts Dillan did

**Review by mlaszloffy — APPROVED** [review]

**Comment by avarsava** [comment]
@djcooke @mlaszloffy I added NextSeq 2000 to the docs in italics to indicate 'in development', ok?

**Comment by djcooke** [comment]
> @djcooke @mlaszloffy I added NextSeq 2000 to the docs in italics to indicate 'in development', ok?

That works since we've only looked at test runs so far

**Pull request merged**
